### ISSUE TITLE
WP 1.0 Bot stops & not create logs

### ISSUE THREAD

**Issue by AfroThundr3007730** [openzim/wikimedia_wp1_bot#8] opened 2018-10-21 23:44 UTC
From phabricator [T207559](https://phabricator.wikimedia.org/T207599)
>''WP 1.0 bot'' is having ongoing issues for several months. It starts daily processing, then stalls out at various WikiProjects, not processing the rest. Lately, it does not get past "B" in the alphabet. The multiple issue reports are at [Wikipedia talk:Version 1.0 Editorial Team/Index](https://en.wikipedia.org/wiki/Wikipedia_talk:Version_1.0_Editorial_Team/Index).
>
>A second issue is that the bot not creating WP logs for many WP since October 8. For example [Wikipedia:Version 1.0 Editorial Team/Catholicism articles by quality log](https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Catholicism_articles_by_quality_log)
and [Wikipedia:Version 1.0 Editorial Team/Saints articles by quality log](https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Saints_articles_by_quality_log).

**Comment by audiodude** [comment] 2018-10-22 20:33
Duplicate of #7

**Closed by audiodude** 2018-10-22 20:33 UTC
